import "./globals.css";
import ReduxProvider from "@/providers/ReduxProvider";
import AuthSync from "@/components/AuthSync"
import ClientProvider from "@/providers/ClientProvider";
import type { Metadata } from "next";
import ToastContainer from "@/components/ToastContainer";


export const metadata: Metadata = {
    title: "Redux Prisma Todo",
    description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className='bg-gray-900'
      >
        <ClientProvider>
          <ReduxProvider>
            <AuthSync />
            <ToastContainer/>
            {children}
          </ReduxProvider>
        </ClientProvider>

      </body>
    </html>
  );
}
